name: boosted_trees_estimator_const_truck
data:
  truck_dataset:
    train: "tensordataTrain.csv"
    eval: "tensordataTest.csv"
hyperparameters:
  n_trees: 653
  max_depth: 11
  learning_rate: 0.0003368435590495161
  l1_regularization: 0.0005158795301189985
  l2_regularization: 0.0013997404534321738
  min_node_weight: 0.0003359855025574565
  global_batch_size: 8
searcher:
  name: single
  metric: accuracy
  max_length:
    batches: 500
  smaller_is_better: false
entrypoint: model_def:BoostedTreesTrial
scheduling_unit: 1
environment:
  image: "determinedai/environments:py-3.8-pytorch-1.12-tf-2.8-cpu-0.21.0"
